### ISSUE TITLE
Hardcoded app id

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/firebase-token-generator#2]
The app id is hardcoded at https://github.com/zooniverse/firebase-token-generator/blob/master/app.js#L17. Could this be added in as an environment variable instead?

**Comment by simoneduca** [comment]
Thanks Rog. What do you mean by environment variable?

**Comment by rogerhutchings** [comment]
After talking with @camallen today, this should probably be put in the production `config.json` file. The app should also error out if the required config variables aren't there.

**Comment by simoneduca** [comment]
Closed via https://github.com/zooniverse/firebase-token-generator/pull/9
